package com.javabykiran.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.ColumnDefault;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "adminlte")
public class Users implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	
	@OneToOne
    @JoinColumn(name="sid",nullable=false)
	private  StateMaster  stateMaster;
	
	private String email;
	private String gender;
	private String mobile;
	private String password;
	private String username;
	private String isDefault="N";
	
	
	public Users() {
		// TODO Auto-generated constructor stub
	}


	public Integer getId() {
		return id;
	}


	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}


	public String getGender() {
		return gender;
	}


	public void setGender(String gender) {
		this.gender = gender;
	}


	public String getMobile() {
		return mobile;
	}


	public void setMobile(String mobile) {
		this.mobile = mobile;
	}


	public String getPassword() {
		return password;
	}


	public void setPassword(String password) {
		this.password = password;
	}


	public String getUsername() {
		return username;
	}


	public void setUsername(String username) {
		this.username = username;
	}
	

	public StateMaster getStateMaster() {
		return stateMaster;
	}


	public void setStateMaster(StateMaster stateMaster) {
		this.stateMaster = stateMaster;
	}


	@ColumnDefault(" 'N' ")
	@Column(name="isDefault", nullable=false, length=45)
	public String getIsDefault() {
		return isDefault;
	}


	public void setIsDefault(String isDefault) {
		this.isDefault = isDefault;
	}


	

}